services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    #     networks:
    #       - johnathanaguilar
    #
    # networks:
    #   johnathanaguilar:
    #     external: true
